services:
  db:
    image: postgres:18-alpine
    container_name: db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - appnet

  pgadmin:
    image: dpage/pgadmin4:9.9.0
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - ./pg-servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - appnet

  backend:
    image: backend:v1.0.0
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    image: frontend:v1.0.0
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  pgdata: {}

networks:
  appnet:
    driver: bridge
